Bump to v1.5.0
- Add '+s' option alias for '--no-silent'
- Revamp saving/restoring of bash options
- Add detailed README.md

diff --git a/log_do b/log_do
--- a/log_do
+++ b/log_do
@@ -22,7 +22,7 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-LOG_DO_VERSION="1.4.1"
+LOG_DO_VERSION="1.5.0"
 
 # Enable logging via log_do
 LOG_DO_VERBOSE=""
@@ -127,7 +127,7 @@ log_opts() {
       --stdout|+out|+stdout) shift; LOG_DO_NO_STDOUT=""; continue; ;;
       
       --silent|-s) shift; LOG_DO_NO_STDOUT="1"; LOG_DO_NO_STDERR="1"; continue; ;;
-      --no-silent) shift; LOG_DO_NO_STDOUT=""; LOG_DO_NO_STDERR=""; continue; ;;
+      --no-silent|+s) shift; LOG_DO_NO_STDOUT=""; LOG_DO_NO_STDERR=""; continue; ;;
 
       --strict) shift; LOG_DO_EXIT_ON_FAILURE="1"; continue; ;;
    --no-strict) shift; LOG_DO_EXIT_ON_FAILURE=""; continue; ;;
@@ -182,7 +182,7 @@ log_do() {
       --stdout|+out|+stdout) shift; LOG_DO_NO_STDOUT=""; continue; ;;
       
       --silent|-s) shift; LOG_DO_NO_STDOUT="1"; LOG_DO_NO_STDERR="1"; continue; ;;
-      --no-silent) shift; LOG_DO_NO_STDOUT=""; LOG_DO_NO_STDERR=""; continue; ;;
+      --no-silent|+s) shift; LOG_DO_NO_STDOUT=""; LOG_DO_NO_STDERR=""; continue; ;;
 
       --strict) shift; LOG_DO_EXIT_ON_FAILURE="1"; continue; ;;
    --no-strict) shift; LOG_DO_EXIT_ON_FAILURE=""; continue; ;;
@@ -212,6 +212,7 @@ log_do() {
     
   fi
   
+  # Execute "$@" in the unpiped stdout/stderr case.
   if [ -n "$LOG_DO_NO_PIPE" ]; then
     "$@"
     local R=$?
@@ -227,16 +228,34 @@ log_do() {
 
     return $R    
   fi
-   
-  # Save shell options.
+  # Execute "$@" in the piped stdout/stderr case.
+
+  # First, save shell options.
   # See: https://unix.stackexchange.com/questions/310957/how-to-restore-the-value-of-shell-options-like-set-x?noredirect=1&lq=1
   # N.B. We can improve on this in bash 4.4 and dash using 'local -'
-  local OPTIONS="$(set +o); set -$- 2>/dev/null"
+  #
+  # Save 'shopt -p' options.
+  # And, using 'shopt -po', save 'set +o' options.
+  # However, extract the history option and save that last so it will be restored last.
+  # And save errexit directly, as its value will not be preserved in the subshell.
+  local _LOG_DO_OPTIONS="$(shopt -p; shopt -po | grep -v ' history$'); ";
+  [[ -o errexit ]] && _LOG_DO_OPTIONS+="set -e; "
+  _LOG_DO_OPTIONS+="$(shopt -po | grep ' history$')"
 
+  # Disable history; original setting will be restored later.
+  set +o history
+
+  # Enable pipefail, so pipeline will return the exit status of the last command to exit with a non-zero status,
+  # allowing us to detect errors in any part of a pipeline.
   set -o pipefail
+
+  # Disable 'set -e' so that we can log any error from "$@" and handle it ourselves.
   set +e
+
+  # Disable any PIPE handler.
   trap "" PIPE
 
+  # Execute "$@", piping stdout and/or stderr through log_pipe (according to options).
   if [ -n "$LOG_DO_NO_LOG_STDERR" ]; then
     ( "$@" ) | log_pipe
   elif [ -n "$LOG_DO_NO_LOG_STDOUT" ]; then
@@ -253,7 +272,7 @@ log_do() {
   fi
 
   # Restore shell options
-  eval "$OPTIONS"
+  eval "$_LOG_DO_OPTIONS"
 
   if [ -n "$LOG_DO_EXIT_ON_FAILURE" ] && [ $R -ne 0 ]; then
     LOG_DO_INDENT=""
